### ISSUE TITLE
Normalizing the data to 0-255

### ISSUE THREAD

**Issue by hockeyob** [rii-mango/NIFTI-Reader-JS#10]
How do I normalize data in the typedData array? Where can I find the min and max values in the header? Math.min.apply(typedData) returns infinity and any math I try to do in the for loops takes a long time to calculate, slowing the progress. My typed data is a float32array if it matters

Thank you for any help you give! I will provide any additional info if you need

**Comment by xgui3783** [comment]
haven't tried the code, but according to the code and the spec, the below should read 

```js
var data = // an ArrayBuffer
var niftiHeader = null,
    niftiImage = null,
    niftiExt = null;

if (nifti.isCompressed(data)) {
    data = nifti.decompress(data);
}

if (nifti.isNIFTI(data)) {
    niftiHeader = nifti.readHeader(data);
    console.log(niftiHeader.cal_min, niftiHeader.cal_max)
}
```

[spec](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/cal_maxmin.html)
[relevant code snippit for nifti 1](https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/src/nifti1.js#L208-L209)
[relevant code snippit for nifti 2](https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/src/nifti2.js#L150-L151)

**Comment by hockeyob** [comment]
Hi xgui, 
cal_min and cal_max are both zero for all of my nii files

**Comment by xgui3783** [comment]
Were they set in the nii file to begin with? If not, you might have to do a
for loop to find min and max.
