### ISSUE TITLE
Huge test file

### ISSUE THREAD

**Issue by neurolabusc** [rii-mango/NIFTI-Reader-JS#17]
Installing this package with NPM requires 36mb of disk space, and can be slow depending on internet connections. Of this, over 33mb is the \tests\data\5D.nii image. It would be great if a smaller test file could be used. 

Here is a version of the image that has been de-hazed and gzip compressed that requires [11mb](https://drive.google.com/file/d/1IVvIvpu64qV96RSHqOCz9DrBmX1QOR80/view?usp=sharing).  However, brain extraction and cropping could further improve file size.

**Comment by rii-mango** [comment]
Can you submit a PR?

**Comment by neurolabusc** [comment]
Mea culpa, I see that this was [addressed by a PR from Nov 5, 2021](https://github.com/rii-mango/NIFTI-Reader-JS/commit/2186795bdfe962a6ce7b9bc226d44d5374747f32) to Github. However, `npm install` still has not been updated. Perhaps the build number needs to be updated to generate a new NPM version (ideally after [PR 16](https://github.com/rii-mango/NIFTI-Reader-JS/pull/16) is included).
