### ISSUE TITLE
dims[5] not taken into account

### ISSUE THREAD

**Issue by NicolasRannou** [rii-mango/NIFTI-Reader-JS#2]
I have a NIFTI_TYPE_UINT8 dataset that contains statistical data. (dims[5] > 1)

Adding the following seems to fix it:
```javascript
nifti.readImage = function (header, data) {
    var imageOffset = header.vox_offset;
    var statisticalData = 1;
    if(header.dims[5]){
      statisticalData = header.dims[5];
    }
    var imageSize = header.dims[1] * header.dims[2] * header.dims[3] * header.dims[4] * statisticalData * (header.numBitsPerVoxel / 8);
    return data.slice(imageOffset, imageOffset + imageSize);
};
```
Test data:
https://drive.google.com/file/d/0ByxJ3QQvklnmMDREQUF3MHl6ZjA/view?usp=sharing

You can try to open the file there to see how it should look:
http://fnndsc.github.io/vjs/#viewers_dicom2D

![screen shot 2016-03-09 at 12 11 52 pm](https://cloud.githubusercontent.com/assets/214063/13633575/2b5d9ccc-e5f0-11e5-907f-87b06dbb149f.png)

Thanks

**Comment by rii-mango** [comment]
Thanks!  I've added a fix for this.
