### ISSUE TITLE
Can not parse dataset

### ISSUE THREAD

**Issue by NicolasRannou** [rii-mango/NIFTI-Reader-JS#3]
Hi, It seems the following dataset is not being parsed properly:

The header looks fine but buffer returned is empty.

https://drive.google.com/file/d/0B2-PspfnvPNgTmxJN3h5cTVMb1U/view?usp=sharing

**Comment by rii-mango** [comment]
Thanks for reporting this.  I think you may be using an older version in which `nifti.readImage()` would not correct the time dimension to 1 if it was 0 in the header.  So if it is 0, when it calculates the size of the image, it comes out to 0.

Try using the [latest build](https://github.com/rii-mango/NIFTI-Reader-JS/tree/master/release/current) and let me know if that doesn't fix it.

**Comment by rii-mango** [comment]
Another possibility...  the slope is 0 in that image.  Be sure you aren't multiplying that in or else everything will be 0 as well.

**Comment by NicolasRannou** [comment]
Thanks - trying it and will let you know.

FYI papaya couldn't display this image.

**Comment by NicolasRannou** [comment]
Thanks update to 0.5.3 worked.

You might have update it in Papaya viewer.

![screen shot 2016-04-13 at 9 02 36 am](https://cloud.githubusercontent.com/assets/214063/14485304/809d7a28-0156-11e6-8a09-1f2e3ac67960.png)
