### ISSUE TITLE
Uncaught ReferenceError: nifti is not defined"

### ISSUE THREAD

**Issue by AkiiLucky** [rii-mango/NIFTI-Reader-JS#32]
Uncaught ReferenceError: nifti is not defined"

**Comment by HuangJia-Le** [comment]
I also have this problem.

**Comment by iamiota** [comment]
`import * as nifti from 'nifti-reader-js'`

Try it.

**Comment by 1isten** [comment]
cdn version missing `nifti` global var

**Comment by hanayik** [comment]
@AkiiLucky , @iamiota , @1isten , @HuangJia-Le ,

I have submitted a new PR (#33) that should address this. When we switch to typescript and esbuild there was a flag omitted which meant we were not building the ESmodule properly. When #33 is merged in, you should be able to use nifti-reader-js from the npm CDN as long as you specify that your `<script>` tags are modules like this:

```html
<script type="module">
    import * as nifti from './nifti-reader.js';
    window.nifti = nifti.default;
    console.log(nifti);
</script>
```
