### ISSUE TITLE
fflate.decompressSync is not a function when using nifti-reader-js (React)

### ISSUE THREAD

**Issue by pcanas** [rii-mango/NIFTI-Reader-JS#39]
**How to reproduce**
1. Clone this repo: https://github.com/Chesneynl/nifti-loader-with-error
2. `yarn install`
3. `yarn dev`

`package.json` dependencies are
```
    "fflate": "^0.8.1",
    "nifti-reader-js": "^0.6.8",
```

**The problem**

We get an error because the fflate functions are not found

<img width="1344" alt="Captura de pantalla 2023-12-07 a las 19 23 13" src="https://github.com/101arrowz/fflate/assets/32467089/decdd94a-1746-4532-a779-1951f26ae3a1">

<img width="748" alt="Captura de pantalla 2023-12-07 a las 19 24 11" src="https://github.com/101arrowz/fflate/assets/32467089/b0df191b-a9a4-4185-b3fb-fdb308061396">

These are found when I am navigating my project, so it might have to do with the bundling...

**Comment by pcanas** [comment]
Could I have an update on this item? Thanks!

**Comment by pcanas** [comment]
Hi @neurolabusc
The issue you refer to is talking about cornerstone's `nifti-image-loader` not the volume one. I do not see the relation.

Also notice that the `yarn-error.log` is already part of the cloned repo (error on our side), if you would run
```
git clone https://github.com/Chesneynl/nifti-loader-with-error.git
cd nifti-loader-with-error 
rm yarn-error.log
yarn install
```
you would not see such error.

Could you provide any more updates on this? Thank you!

**Comment by neurolabusc** [comment]
@pcanas here is a [minimal demo](https://github.com/neurolabusc/NIFTI-Reader-Demo) which uses yarn to install and run nifti-reader-js. The example reads a compressed NIfTI file (which uses fflate for new versions, and pako for older versions of nifti-reader-js:

```
git clone git@github.com:neurolabusc/NIFTI-Reader-Demo.git
cd NIFTI-Reader-Demo
yarn install
yarn start
```

I am not familiar with yarn or cornerstone. While cornerstone is legendary for DICOM-support, you may want to consider NiiVue if your interest in NIfTI images (as well as meshes, connectomes and tractography). You can see a lot of [live demos here](https://niivue.github.io/niivue/), it is also embedded into a lot of React frameworks, including those shown [here](https://github.com/niivue) as well as OpenNeuro.

A minimal HTML page would be:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>NiiVue</title>
  </head>
  <body>
    <canvas id="gl" width="640" height="640"></canvas>
  </body>
  <script type="module" async>
    import * as niivue from "https://niivue.github.io/niivue/dist/index.js";
    var volumeList = [
      { url: "https://niivue.github.io/niivue-demo-images/mni152.nii.gz" },
    ];
    var nv = new niivue.Niivue({ isResizeCanvas: false });
    nv.attachTo("gl");
    nv.loadVolumes(volumeList);
  </script>
</html>
```
