### ISSUE TITLE
How to get image data to draw on canvas?

### ISSUE THREAD

**Issue by hanayik** [rii-mango/NIFTI-Reader-JS#5]
Hi guys/gals,

Is there an example anywhere showing how to get the image data from the ArrayBuffer and use it to draw the nifit slices on a canvas? I'm able to read in the header just fine using code similar to the example in the main "readme" for this repo. Do I need to loop through the niftiImage bytes manually and piece everything together, or am I missing something where that has been handled by another function?

Here's the code I'm using to load the image:

```
const fs = require('fs')
const nifti = require('nifti-reader-js')

brainFile = './T1_T017.nii'

data = fs.readFileSync(brainFile).buffer

var niftiHeader = null,
    niftiImage = null,
    niftiExt = null;

if (nifti.isCompressed(data)) {
    data = nifti.decompress(data);
}

niftiHeader = nifti.readHeader(data);
console.log(niftiHeader.toFormattedString());
niftiImage = nifti.readImage(niftiHeader, data);

```

**Comment by martinezmj** [comment]
What in the NIFTI file is raw data, not something that can be put onto a canvas without conversion.  You need to convert the raw image data to rgb data.  You can see some examples here in the Papaya viewer: https://github.com/rii-mango/Papaya/blob/master/src/js/viewer/screenslice.js

You'll need to calculate the ratio of the image data range to the screen data range (255).  For example say your nifti data goes from 1000 (black on screen) to 5000 (white on screen):
```
screenRatio = 255 / (screenMax - screenMin)
screenRatio = 255 / (5000 - 1000);
```
Then for each image data value in the nifti file, you can calculate what the RGB value is:
```
screenValue = (value - screenMin) * screenRatio
screenValue = (value - 1000) * screenRatio
```
Then you'll set the rgb data for each pixel in your canvas like:
```
imageDataDraw = myContext.createImageData(x, y);
imageDataDraw.data[index] = (screenValue >> 16) & 0xff;
imageDataDraw.data[index + 1] = (screenValue >> 8) & 0xff;
imageDataDraw.data[index + 2] = (screenValue) & 0xff;
imageDataDraw.data[index + 3] = alpha;
```
Hope this helps!

**Comment by rii-mango** [comment]
I've posted an example of how to read and draw a nifti to a canvas: https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/tests/canvas.html

**Comment by barefoothiker** [comment]
Thanks so much!!! This works for me. I see a coronal slice for the Nifti image I have. I guess I need to reorient the image the view the other slices? I guess accessing the niftiImage data I have using the appropriate indices when viewing the sagittal or transverse sections would be complicated and inefficient.

**Comment by rii-mango** [comment]
You can pull out any slice direction you want from the data, you just need figure out how to index the pixels.  It sounds like your data is ordered as xzy -- so x=cols, z=rows, y=slices -- you could pull out an axial or sagittal slice from this data by calculating the appropriate indices.  The nifti orientation will tell you how to map from col-row-slice to x-y-z in the real world, if that's what's needed.

**Comment by MathisGuilhin** [comment]
Hello guys,
@rii-mango I don't quite understand how to manage with indices.
Im using the canvas example and now I would like to pull out the axial and sagittal slice, but I don't know how to calculate the appropriate indices. Could you give a few hints please ?
Many thanks in advance,
Matt

**Comment by hockeyob** [comment]
@MathisGuilhin Did you ever figure out how to pull axial and sagittal slices? I am trying to do the same things and I am running into many issues
